config/routes.rb
Rails.application.routes.draw do

  get 'about' => "abouts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: :show do
    
    resource :profile
    member do
      get :articles
      get :comments
      get :like_articles

      get :draft
      get :favorite

      get :friends
    end
  end

  resources :friends do 
    member do
      get :send_invitation
      get :cancel_invitation
      get :accept_invitation
      get :ignore_invitation
      get :reject_invitation
      get :block_my_friend
      get :unblock_my_friend
      post :select_relation_tag
    end
  end

  resources :articles do
    resources :comments
    member do
      post :add_favorite
      post :remove_favorite
      post :like
      get :like_users
      post :move
    end
  end

  namespace :admin do
    resources :articles
    resources :categories
    resources :users
  end

  root :to => 'articles#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :article, :counter_cache => true
	belongs_to :user
	
	validates_presence_of :content	


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, :find_article_and_comments

	def new
		@comment = Comment.new
	end

	def create		
		if current_user
			@comment = Comment.new(params_comment)
			@comment.user =current_user
			@comment.article = @article
			if @comment.save		
				# @comment.article.touch(:last_comment_at)
				
				@new_comment = Comment.new					
				@notice = 'your comment has been successful posted'
			else
				@alert = @comment.errors.full_messages.join(' ').html_safe
				render 'new'
			end

		else
			redirect_to new_session(:user)
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		@comment.update(params_comment)
		if @comment.save
			@notice = "your comment has been successfully updated"
			@new_comment = Comment.new

		else
			@alert = @comment.errors.full_messages.join(' ').html_safe
		end
	end


	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		@new_comment = Comment.new
		@notice = "You comment has been successfully deleted"
	end

private
	def params_comment
		params.require(:comment).permit(:content)
	end

	def find_article_and_comments
		@article = Article.find(params[:article_id])
		@comments = @article.comments
	end

	def refresh
		respond_to do |format|
			format.js {
				render 'comments/refresh'
			}
		end
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%# article, comment %>
<% if current_user %>
	<% if comment.new_record? %>
		<%= form_for comment, :url => article_comments_path(article), :remote=> true do |form| %>
		<%= form.label :content,("Hi #{link_to current_user.username, user_path(current_user)}, post your comment").html_safe %>

			<br>
			<%= form.text_area :content, :class=>"text-area" %>
			<br>
			<%= form.submit "Post", :class=>"btn btn-primary done"%>
		<% end %><!-- form for -->

	<% else %>
		<%= form_for comment, :url => article_comment_path(article, comment), :method => :patch, :remote=>true do |form| %>
		<%= form.label :content,("Hi #{link_to current_user.username, user_path(current_user)}, update your comment").html_safe %>
		<br>
		<%= form.text_area :content, :class=>"text-area" %>
		<br>
		<%= link_to "Cancel", new_article_comment_path, :remote=>true, :class=>"btn btn-default done"%>
		<%= form.submit "Update", :class=>"btn btn-info done"%>
		<% end %><!-- form for -->

	<% end %><!-- comment.new_record? -->

<% else %>
	<%= link_to "Sign-in to post your comment", user_session_path, :class=>"btn btn-primary" %>

<% end %><!-- if current_user  -->

app/views/comments/_new_comment.html.erb
<%c = @comment %>
<tr>
	<td> <% if c.user %> 
		<%= link_to c.user.username, user_path(c.user) %>
		<% end %>
	</td>
	<td> <%=c.content %> </td>
	<td> <%=c.updated_at %></td>
	<td> <%= if c.user == current_user 
				 link_to "Edit", article_path(c.article, :comment_id=>c.id) 
				 end %>
	</td>
	<td> <%= if c.user == current_user
				 link_to "Delete", comment_path(c.article, :comment_id=>c.id), :method=>"delete", :remote=>true, :data=>{:confirm=>"Are you sure?"}, :id=>"comment-#{c.id}"
				 end %>


  </td>
</tr>

app/views/comments/_notice.js.erb
<% if @notice %>
	$('.article-comments .note').addClass("comment-notice").text("<%=@notice%>")
<% else %>
	$('.article-comments .note').removeClass("comment-notice")
<% end %>

<% if @alert %>
	$('.article-comments .note').addClass("comment-alert").text("<%=@alert%>")
<% else %>
	$('.article-comments .note').removeClass("comment-alert")	
<% end %>

app/views/comments/_row.html.erb
<%# c, article %>
<tr class="comment-row-<%= c.id %>">
	<td> <% if c.user %> 
		<%= link_to c.user.username, user_path(c.user) %>
		<% end %>
	</td>
	<td> <%=c.content %> </td>
	<td><%= time_ago_in_words(c.updated_at) %></td>
	<td> <%= if c.user == current_user 
				 link_to "Edit", edit_article_comment_path(article, c) , :remote=>true
				 end %>
	</td>
	<td> <%= if c.user == current_user
				 link_to "Delete", article_comment_path(article, c), :method=>"delete", :remote=>true, :data=>{:confirm=>"Are you sure?"}, :id=>"comment-#{c.id}"
				 end %>

	</td>
</tr>

app/views/comments/create.js.erb
$('.article-comments .post').html("<%= j (render :partial=> 'form', :locals=> {:comment => @new_comment, :article=> @article}) %>")
$('.article-comments .table .table-head').after("<%= j (render :partial => 'row', :locals => {:c => @comment, :article=>@article}) %>")

<%= render :partial => 'notice.js' %>

app/views/comments/destroy.js.erb
$('.article-comments .post').html("<%= j (render :partial=> 'form', :locals=> {:comment => @new_comment, :article=> @article}) %>")
$('.comment-row-<%= @comment.id %>').remove();
<%= render :partial => 'notice.js' %>

app/views/comments/edit.js.erb
$('.article-comments .post').html("<%= j (render :partial=> 'form', :locals=> {:comment => @comment, :article=> @article}) %>")

<%= render :partial => 'notice.js' %>

app/views/comments/new.js.erb
$('.article-comments .post').html("<%= j (render :partial=> 'form', :locals=> {:comment => @comment, :article=> @article}) %>")

<%= render :partial => 'notice.js' %>

app/views/comments/refresh.js.erb
$('.article-comments').html("<%= j (render :partial => 'article_comments', :locals => {:comments => @comments,:comment=>@comment,:article=>@article}) %>")
$('.article-comments .note').text("")
<% if @notice %>
	$('.article-comments .note').addClass("comment-notice").text("<%=@notice%>")
<% else %>
	$('.article-comments .note').removeClass("comment-notice")
<% end %>

<% if @alert %>
	$('.article-comments .note').addClass("comment-alert").text("<%=@alert%>")
<% else %>
	$('.article-comments .note').removeClass("comment-alert")	
<% end %>

app/views/comments/update.js.erb
$('.article-comments .post').html("<%= j (render :partial=> 'form', :locals=> {:comment => @new_comment, :article=> @article}) %>")
var prev = $('.comment-row-<%= @comment.id %>').prev();
prev.end().remove();
prev.after("<%= j (render :partial => 'row', :locals => {:c => @comment, :article=>@article}) %>")

<%= render :partial => 'notice.js' %>