config/routes.rb
Rails.application.routes.draw do

  get 'about' => "abouts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: :show do
    
    resource :profile
    member do
      get :articles
      get :comments
      get :like_articles

      get :draft
      get :favorite

      get :friends
    end
  end

  resources :friends do 
    member do
      get :send_invitation
      get :cancel_invitation
      get :accept_invitation
      get :ignore_invitation
      get :reject_invitation
      get :block_my_friend
      get :unblock_my_friend
      post :select_relation_tag
    end
  end

  resources :articles do
    resources :comments
    member do
      post :add_favorite
      post :remove_favorite
      post :like
      get :like_users
      post :move
    end
  end

  namespace :admin do
    resources :articles
    resources :categories
    resources :users
  end

  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	
	has_many :comments, -> { order("id DESC") }

	belongs_to :user, :foreign_key => :author_id
	has_many :article_categoryships
	has_many :categories, :through => :article_categoryships
	has_many :article_views
	has_many :favorites
	has_many :user_favorites, :through=>:favorites, :source=>:user
	has_many :likes
	has_many :like_users, :through=>:likes, :source=>:user
	has_many :taggings
	has_many :tags, :through=>:taggings, :source=>:tag

	validates :author_id, presence: true
	validates :title, presence: true, :unless => :status_draft?

	validate :check_categories

	validates_presence_of :content, unless: :status_draft?

	def category_names
		self.categories.map{ |x| x.name}.join(" ")
	end

	def published?
		status == "published"
	end

	def status_draft?
		status == "draft"
	end

	def view!(user)
		self.article_views.find_or_create_by( :user_id => user.id )
	end

  def tag_list
    self.tags.map{|x| x.name}.join(",")
  end

  def tag_list=(str)
    ids = str.split(',').map do |tag_name|
      tag_name.strip!
      tag = Tag.find_by_name(tag_name)||Tag.create(:name=>tag_name)
      tag.id
    end
    self.tag_ids = ids
  end

	protected

	def check_categories
		if self.categories.empty?
			errors[:base] = "Must select one category!"
		end
	end

end

app/models/article_view.rb
class ArticleView < ActiveRecord::Base

	belongs_to :article, :counter_cache => "views_count"
	belongs_to :user

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_admin


	def index
		@page = params[:page].to_i ||= 0
		@per = 20
		@articles = Article.all.page(@page).per(@per)

	end


end
	

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :authenticate_user!, :except=>[:index, :show, :about]

	def index
		set_article_list
		@articles = @articles.page(params[:page]).per(10)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(post_article_params)
		
		@article.user = current_user

		if params[:commit] == 'Publish'
			@article.status = 'published'
			if @article.save
				flash[:notice] = "You had posted one article"
				redirect_to articles_path
			else
				@article.status = "draft"
				render :new
			end

		elsif params[:commit] == 'Save'
			@article.status = 'draft'
			if @article.save
				flash[:notice] = "You had saved one article, not published yet"
				redirect_to user_path(current_user)
			else
				render :new				
			end
		end
	end

	def edit
		@article = current_user.post_articles.find(params[:id])
	end

	def update
		@article = current_user.post_articles.find(params[:id])

		if params[:commit] == "Update"
			if @article.update(post_article_params)
				flash[:notice] = "You had updated your article"
				redirect_to article_path(@article)
			else
				render :edit
			end
		elsif params[:commit] == 'Publish'
			@article.status = "published"
			if @article.update(post_article_params)

				flash[:notice] = "You had posted your article"
				redirect_to article_path(@article)
			else
				@article.status = "draft"
				render :edit
			end

		elsif params[:commit] == 'Save'
			if @article.update(post_article_params)
				flash[:notice] = "You had saved your article, not published yet"
				redirect_to user_path(current_user)
			else
				render :edit
			end
		end
	end

	def destroy
		@delete_article = current_user.articles.find(params[:id])
		if @delete_article.destroy
			flash[:notice] = "You had deleted your article"
			redirect_to articles_path
		end
	end

	def show
		@article = Article.find( params[:id] )
		@poster = @article.user

		@comments = @article.comments

		@comment = Comment.new		

		if current_user
			@favorite = current_user.favorites.find_by_article_id(@article.id)

			@like = Like.find_by_user_article(current_user,@article)
			@article.view!(current_user)
		end	

	end

	def add_favorite
		@favorite = current_user.favorites.build( :article_id=> params[:id] )

		if @favorite.save
			flash[:notice]= "You have saved the favorite to this article"
			redirect_to article_path(params[:id])
		else
			render :show
		end
	end

	def remove_favorite
		@favorite = current_user.favorites.find_by_article_id( params[:id] )

		if @favorite.destroy
			flash[:notice]= "You have removed the favrite to this article"
			#redirect_to article_path(params[:id])
			redirect_to :back
		else
			render :show
		end
	end

	def like
		@article = Article.find( params[:id] )		
		@like = current_user.likes.find_by_article_id(params[:id])

		unless @like
			@like = current_user.likes.create(:article_id=>params[:id])
		else
			@like.destroy
			@like = Like.new
		end

		respond_to do |format|
			format.json {
				html = render_to_string :partial => 'articles/like.html', :locals=>{:like=>@like, :article=>@article}
				render :json => { :html => html }
			}
			format.js {
				render 'articles/like'
			}
		end

	end

	def like_users
		@article = Article.find( params[:id] )	

		respond_to do |format|
			format.js {
				render 'articles/like_users'
			}
		end
		
	end

	private

	def post_article_params	
		params.require(:article).permit(:title,:content,:tag_list,:category_ids => [])
	end

	def set_article_list
		@articles = @category? @category.articles : Article.all
		@articles = @articles.where( :status => 'published' )

		if params[:order] == 'comment'
      @articles = @articles.order('comments_count desc')
		elsif params[:order] == 'views'
      @articles = @articles.order('views_count desc')			
    elsif params[:order] == 'last_comment'
    	@articles = @articles.order('last_comment_at desc')
    else
    	@articles = @articles.order('updated_at desc')
		end
	end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def status_published?
		:status == "published"
	end

	def display_category(categoies)
		arr = categoies.map { |c|
			content_tag(:span, c.name, :class => "label label-primary" )
		}

		safe_join(arr, " ")
	end

	def display_tag(tags)
		arr = tags.map{|t| 
				content_tag(:span, t.name, :class=>"label label-primary")
		}
		safe_join(arr," ")
	end

end

app/views/articles/_like.html.erb
<%# input like, article %>

<% like_word = like.new_record? ? "Like" : "Dislike" %>
<span class="like_update"><%= link_to like_word, like_article_path(article), :remote => true, :data => { :type => :json }, :method => :post, :class => "btn btn-info" %>
<% word= ''%>
<% if article.likes.count == 0 %>
<% word = "no like" %>
<% elsif article.likes.count == 1 %>
<% word = "1 like" %>
<% else %>
<% word = "Total #{article.likes.count} likes" %>
<% end %>
<%= link_to word, like_users_article_path(article), :class=>"like_users", :"data-toggle"=>"modal", :"data-target"=>"#myModal", :type=>"button", :remote=>true %>
</span>

app/views/articles/_like_users.html.erb
<% @article.like_users.each do |u| %>
<p>
	<%= image_tag u.user_profile.image.url(:thumb) %>
	<%= link_to u.username, user_path(u) %>
</p>
<% end %>

app/views/articles/_post_form.html.erb
	<div class="unit title">
		<div class="key">
			<%= form.label :title, "Title" %>
		</div>
		<div class="value">
			<%= form.text_field :title %>
		</div>
	</div>

	<div class="unit category">
		<div class="key">
		<%= form.label :category_id, "Class" %>
		</div>
		<div class="value">
		<%= form.collection_check_boxes(:category_ids, Category.all, :id, :name,:class=>"article-form-category-checkbok") %>
		</div>
	</div>

	<div class="unit tag">
		<div class="key">
			<%= form.label :tag_list, "Tag" %>
		</div>
		<div class="value">
			<%= form.text_field :tag_list, :class=>"tag_input" %>
		</div>
	</div>

	<div class="unit content">
		<div class="key">
		<%= form.label :content, "Content" %>
		</div>
		<div class="value">
		<%= form.text_area :content %>
		</div>
	</div>

<script type="text/javascript">
	$('.tag .tag_input').select2({
		tags:<%= raw(Tag.all.map{|t| t.name}.to_json) %>,
		tokenSeparators: [',',' ']
	})


</script>

app/views/articles/about.html.erb
<%= render :partial => "side_bar/category", :locals =>{:path=>"back"}%>

<div class="content-center" id="about-content">
	<div class="about-box">
		<table class="table">
			<tr><td>Total users</td><td><%=@total_users%></td></tr>
			<tr><td>Total articles</td><td><%=@total_articles%></td></tr>
			<tr><td>Total comments</td><td><%=@total_comments%></td></tr>
		</table>
	</div>
</div>

app/views/articles/edit.html.erb
<%= render :partial => "side_bar/category", :locals =>{:path=>"back"}%>

<div class="content-center">
	
	<div class="article-meta">
		<div class="info">
			<!-- show information -->	
			<h2 class="title">You're editting the article</h2>

			<!-- poster -->
			<div class="user">
				<div><%= image_tag avatar_url(current_user)%></div>
				<p class="poster">Poster: <%=current_user.username %></p>
			</div>
		
			<div class="status">
				<% if @article.published? %>
					<p> Published at <%= @article.updated_at %> </p>
				<% else %>
				<p> Not published yet </p>
				<% end %>
			</div>
		</div>

		<div class="edit-it">
		</div><!-- edit-it -->
	</div><!-- article-meta -->

	<div class="single-article-content">
		<%= form_for @article, :url=>article_path, :method=>:patch do |form| %>

			<%= render :partial => "post_form", :locals =>{:form=>form}%>

		<div class="do-it">
			<% if @article.status == "published" %>
				<%= form.submit "Update", :class=>"btn btn-warning"%>
		
			<% elsif @article.status == "draft" %>
				<%= form.submit "Publish", :class=>"btn btn-warning"%>
				<%= form.submit "Save", :class=>"btn btn-info"%>
			<% end %>
			<%= link_to "cancel",article_path, :class=>"btn btn-primary"%>
		</div>
		<% end %><!-- form -->
	<div><!-- article-content -->

</div><!-- content-center -->

app/views/articles/index.html.erb
<%= render :partial => "side_bar/category", :locals =>{:path=>"post"}%>


<div class="content-center">

	<div class="article-title">
		<h1>
			<% if @category %>
				<%= @category.name %>
			<% else %>
			All
			<% end %>
		</h1>
	</div><!--article-title -->

	<div class="article-content">
		<div class="paginate">
			<%= paginate @articles %>
		</div>
		<table class="table table-hover">
			<tr>
				<th class="index text-center"></th>
				<th class="topic text-center">Topic</th>
				<th class="tag text-center">Tag</th>
				<th class="category text-center">Category</th>
				<th class="poster text-center">Post User</th>
				<th class="date text-center">
						<%= link_to "Posted date",articles_path(order: :updated_at) %>
				</th>
				<th class="last_comment text-center">
						<%= link_to "Last comment",articles_path(order: :last_comment) %>
				</th>
				<th class="comment text-center">
						<%= link_to "Comment",articles_path(order: :comment) %>
				</th>
				<th class="views text-center">
						<%= link_to "Views",articles_path(order: :views)%>
				</th>
			</tr>

				<% @articles.each_with_index do |a, index| %>
			<tr>
				<td>
					<%= get_serial(@articles, index) %>
				</td>
				<td>
					<%= link_to a.title, article_path(a) %>
				</td>
				<td>
					<%= display_tag(a.tags) %>
				</td>
				<td class="text-center">
					<p><%= display_category(a.categories) %></p>
				</td>

				<td class="text-center">
					<% if a.user %>
						<%= link_to a.user.username, user_path(a.user) %>
					<% end %>
				</td>

				<td class="text-center">
					<%= a.updated_at.to_s(:short) %>
				</td>

				<td class="text-center">
					<%= a.last_comment_at.try(:to_s, :short) %>
				</td>

				<td class="text-center">
					<%= a.comments_count %>
				</td>

				<td class="text-center">
					<%= a.views_count %>
				</td>				

			</tr>
				<% end %><!-- @articles.each -->
		</table>
	</div><!-- article-content -->
</div>

app/views/articles/like.js.erb
$('.like_update').html("<%= j (render :partial => 'like', :locals=>{:like=>@like, :article=>@article}) %>")

app/views/articles/like_users.js.erb
$('.article-like-users').html("<%= j (render :partial => 'like_users') %>")

app/views/articles/new.html.erb
<%= render :partial => "side_bar/category", :locals =>{:path=>"back"}%>

<div class="content-center">
	
	<div class="article-meta">
		<div class="info">
			<!-- show information -->
			<h2 class="title"> New Article</h2>

				<!-- poster -->
			<div class="user">
				<div><%= image_tag avatar_url(current_user)%></div>
				<p class="poster">Poster: <%=current_user.username %></p>
			</div>

		</div><!-- user_info -->

		<div class="status">
			<p>New article</p>
		</div>

		<div class="edit-it">
		</div><!-- edit-it -->
	</div><!-- article-meta -->


	<div class="single-article-content">
		<%= form_for @article, :url=>articles_path do |form| %>

		<%= render :partial => "post_form", :locals =>{:form=>form}%>
	
		
		<div class="do-it">
			<%= form.submit "Publish", :class=>"btn btn-warning"%>
			<%= form.submit "Save", :class=>"btn btn-info"%>
			<%= link_to " Cancel", articles_path,:class=>"btn btn-default"%>
		</div>

		<% end %><!-- form -->
	</div><!-- article-content -->

</div><!-- content-center -->

app/views/articles/show.html.erb
<%= render :partial => "side_bar/category", :locals =>{:path=>"back"}%>

<div class="content-center">
	
	<div class="article-meta">
		<div class="info">
			<!-- show information -->
			<h2 class="title"><%= @article.title %></h2>

			<!-- poster -->
			<div class="user">
				<div><%= image_tag avatar_url(@article.user)%></div>
				<p class="poster"><%=@poster.username %></p>
			</div>

			<div class="status">
				<p>publised at <%= @article.updated_at %></p>
			</div>

			<div class="category">
				<p>category: <% @article.category_names %></p>
			</div>

		</div><!-- user-info -->

		<div class="edit-it">
			<!-- add or remove favroite -->
			<p>
				<% if current_user %>
					<% unless @favorite %>
					<%= button_to "Add to My favorite", add_favorite_article_path(@article), :class=>"btn btn-primary" %>
					<% else %>
					<%= button_to "Remove from My favorite", remove_favorite_article_path(@article), :class=>"btn btn-warning" %>
					<% end %>
					<%= render :partial=>"like", :locals=>{:like=>@like, :article=>@article} %>
				<% end %>
			</p>

			<!-- Edit and delete -->	
			<% if @article.user == current_user %>
			<p class="edit"><%= link_to "Edit",edit_article_path(@article),:class=>"btn btn-info"%></p>


				<% if current_user.role = "admin" %>
				<p class="article-show-info-delete"><%= link_to "Delete",article_path(@article), :method=>:delete, :class=>"btn btn-danger", :data=>{:confirm=>"Are you sure?"}%></p>
				<% end %>
			<% end %>
		</div><!-- edit-it -->
	</div><!-- article-meta -->


	<!-- show content -->
	<div class="single-article-content show-body">
		<p><%= simple_format(@article.content) %></p>
	</div>


	<!-- comments -->
	<div class="article-comments">

		<div class="title">
			<h4>Reply</h4>
			<%= content_tag(:div, "", :class=>"note") %>
		</div>

		<div class="post">
			<%= render partial: 'comments/form', locals: {comment: @comment, article: @article} %>

		</div>

		<table class="table table">
			<tr class="table-head">
				<th>Poster</th><th>Comment</th><th>Post time</th><th></th><th></th>
			</tr>
		<% if @comments.count>0 %>
			<% @comments.each do |c| %>
					<%= render partial: 'comments/row', locals: {c: c, article: @article} %>
			<% end %><!-- @comments -->

		<% else %>

			<tr class="no-reply">
				<td colspan="5">
					<p>No any reply</p>
				</td>
			</tr>
		<% end %><!-- if @comments.count>0 -->
		</table>



	</div><!-- article-comments -->


	<!-- FB like-->
	<div class="article-FB">
		<div class="fb-like" data-href="https://developers.facebook.com/docs/plugins/" data-width="100" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>

		<div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.3";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
		</script>
	
	</div>

</div><!-- content-center -->


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"> description</h4>
      </div>
      <div class="modal-body article-like-users">

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>

<script>
$('.edit-it .like_update').on('ajax:success', function(evt, data){
	  $(this).html( data.html );
});

</script>