config/routes.rb
Rails.application.routes.draw do

  get 'about' => "abouts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: :show do
    
    resource :profile
    member do
      get :articles
      get :comments
      get :like_articles

      get :draft
      get :favorite

      get :friends
    end
  end

  resources :friends do 
    member do
      get :send_invitation
      get :cancel_invitation
      get :accept_invitation
      get :ignore_invitation
      get :reject_invitation
      get :block_my_friend
      get :unblock_my_friend
      post :select_relation_tag
    end
  end

  resources :articles do
    resources :comments
    member do
      post :add_favorite
      post :remove_favorite
      post :like
      get :like_users
      post :move
    end
  end

  namespace :admin do
    resources :articles
    resources :categories
    resources :users
  end

  root :to => 'articles#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  before_create :set_role
  validates_presence_of :friendly_id, :username
  validates_uniqueness_of :friendly_id, :username

  has_one :user_profile, :dependent => :destroy
  has_many :post_articles, :class_name=> "Article", :foreign_key => "author_id"
  has_many :comments
  has_many :reply_articles, :through  => :comments, :source=>:article
  has_many :article_views
  has_many :favorites
  has_many :favorite_articles, :through =>:favorites, :source=>:article
  has_many :create_categories, :class_name => "Category", :foreign_key => :creator_id
  has_many :likes
  has_many :like_articles, :through => :likes, :source=>:article

  accepts_nested_attributes_for :user_profile, :allow_destroy => true, :reject_if => :all_blank
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :friend_relation_tags, :through => :friendships

  def self.check
    Rails.logger.debug(current_user.inspect)
  end

  def to_param
    self.friendly_id
  end

  def admin?
    self.role == "admin"
  end

  def set_role
    self.role = "user"
  end

  def self.from_omniauth(auth)
    user = User.find_by(:provider=>auth.provider,:uid=>auth.uid)
    if user
      return user
    end

    new_user = User.find_by_email(auth.info.email)
    unless new_user
      new_user = User.new
      new_user.email = auth.info.email
      new_user.password = Devise.friendly_token[0,20] 
      new_user.username = auth.info.name

    end
    new_user.build_user_profile unless new_user.user_profile
    new_user.provider = auth.provider
    new_user.uid = auth.uid
    new_user.token = auth.credentials.token
    new_user.user_profile.image = auth.info.image.sub('http','https')
    new_user.user_profile.first_name = auth.info.first_name
    new_user.user_profile.last_name = auth.info.last_name
    new_user.save
    new_user
    # user.image = auth.info.image # assuming the user model has an image
  end

# Don't understand this method
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_user!, :except=>:show
	before_action :authenticate_admin

	def index
		@page = params[:page].to_i ||= 0
		@per = 20
		@users = User.all.page(@page).per(@per)

	end


	def show
		@user = User.find(params[:id])		

	end

	def edit
		@user = User.find(params[:id])
	end


	def update
		@user = User.find(params[:id])	
		if @user.update(user_params)
			flash[:notice]="You've updated #{@user.username}'s profile successfully"
			redirect_to admin_user_path(@user)
		else
			render :edit
		end	
	end

	def destroy
		@user = User.find(params[:id])
		if @user.destroy
			flash[:notice]="You've deleted this user's account successfully"
			redirect_to admin_users_path
		else
			render :index
		end
	end


private

	def user_params	
		params.require(:user).permit(:username, :role,
										:user_profile_attributes => [:first_name, :last_name, :english_name, :birthdate, :intro])

	end


end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, except: [:show, :show_profile, :posted_articles, :posted_comments]
	before_action :set_user 

	def show
		redirect_to user_profile_path(@user)
	end

	def articles
		@post_articles = @user.post_articles.where("status = 'published'").order(:updated_at => :desc)
		render :template =>"users/articles"
	end

	def comments
		@comments = @user.comments.order(:updated_at => :desc)
		render :template =>"users/comments"
	end

	def like_articles
		@like_articles = @user.like_articles
	end

	def draft
		@draft_articles = @user.post_articles.where("status = 'draft'").order(:updated_at => :desc)
	end

	def favorite
		@favorite_articles = @user.favorite_articles.order("favorites.updated_at desc")

	end

	def friends
		@friendships = @user.friendships
		@completed_friendships = @friendships.map{|fs| fs if fs.status=="completed"}.compact
		@invited_friendships = @friendships.map{|fs| fs if fs.status=="invited"}.compact
		@other_friendships = @friendships - @invited_friendships - @completed_friendships
	end

private
	
	def set_user
		@user = User.find_by_friendly_id(params[:id])
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friends_completed.html.erb
<%# :locals=>{:completed_friendships=>@completed_friendships} %>

<h4>My friends (<%= completed_friendships.count %>)</h4>
<table class="table">
	<tr>
		<th class="username">Title</th>
		<th class="relation">Relation</th>
		<th class="Edit-it"></th>
	</tr>
	<% completed_friendships.each do |fs| %>
		<tr>
			<td> <%= link_to fs.friend.username, user_path(fs.friend) %> </td>
			<td> 
					<%= collection_select fs,:friend_relation_tag_id, FriendRelationTag.all,:id,:name,{:selected =>fs.friend_relation_tag_id},:data=>{:url=>select_relation_tag_friend_path(fs.friend)
						}, :class=>"relation_select" %>
			</td>
			<td> <%= link_to "Block", block_my_friend_friend_path(fs.friend,:user=>true), :remote=>true,:data=>{:confirm=>"Are you sure?"}%>
			</td>
		</tr>
	<% end %><%# if friendships.each %>
</table>

app/views/users/_friends_new.html.erb
<%# :locals=>{:invited_friendships=>@invited_friendships} %>
<% if invited_friendships.count >0 %>

<h4>My invitations (<%= invited_friendships.count %>)</h4>
<table class="table">
	<tr>
		<th class="username">Username</th>
		<th></th>
	</tr>
	<% invited_friendships.each do |fs| %>
		<tr>
			<td> <%= link_to fs.friend.username, user_path(fs.friend) %> </td>
			<td> 
				<%= link_to "Accepted", accept_invitation_friend_path(fs.friend,:user=>true), :remote=>true, :class=>"btn btn-primary" %>
				<%= link_to "Ignore", ignore_invitation_friend_path(fs.friend, :user=>true), :remote=>true, :class=>"btn btn-info"%>
			</td>
		</tr>
	<% end %><%# if friendships.each %>
</table>

<% end %><%# invited_friendships.count >0 %>

app/views/users/_friends_other.html.erb
<%# :locals=>{:other_friendships=>@other_friendships} %>

<h4>Other users (<%= other_friendships.count %>)</h4>
<table class="table">
	<tr>
		<th class="username">Username</th>
		<th class="status">Status</th>
		<th class="Edit-id"></th>
	</tr>
	<% other_friendships.each do |fs| %>
		<tr>
			<td> <%= link_to fs.friend.username, user_path(fs.friend) %> </td>
			<td> <%= fs.status %></td>
			<td> 
				<% if fs.status == "block" %>
					<%= link_to "Unblock", unblock_my_friend_friend_path(fs.friend,:user=>true),  :remote=>true %>
				<% elsif fs.status == "pending" %>
					<%= link_to "Accept", accept_invitation_friend_path(fs.friend, :user=>true), :remote=>true %>
				<% end %>
			</td>
		</tr>
	<% end %><%# if friendships.each %>
</table>

app/views/users/_user_info.html.erb
<%# :locals=>{:user=>@user, :friendship=>@friendship} %>
	<%= image_tag @user.user_profile.image.url(:thumb) %>
	<div><%= image_tag avatar_url(@user)%></div>
	<h3><%= @user.username %></h3>

	<% if user != current_user  %>
	<p class="friend"> <%= render :partial=>"friends/friend_button", :locals=>{:user=>@user,:friendship_status =>@friendship_status}%> </p>
	<% end %>

app/views/users/articles.html.erb
<%= render :partial => "side_bar/user", :locals =>{}%>


<div class="content-center">
	<div class="user-info">
		<%= render :partial=>"users/user_info", :locals=>{:user=>@user} %>
	</div>

	<div class="user-title">
		<h4>Posted articles (<%= @post_articles.count %>)</h4>
	</div>

	<div class="user-content user-articles">
		<table class="table">
			<tr>
				<th class="index"></th>
				<th class="title">Title</th>
				<th class="comment">Comment</th>
				<th class="update">Update Date</th>
			</tr>
			<% @post_articles.each_with_index do |a,index| %>
			<tr>
				<td class="index"><%= index+1 %></td>
				<td class="title"><%= link_to a.title, article_path(a) %></td>
				<td class="comment"><%= a.comments.count %></td>
				<td class="update"><%=a.updated_at%></td>
			</tr>
			<%end %>
		</table>
	</div>
</div>

app/views/users/comments.html.erb
<%= render :partial => "side_bar/user", :locals =>{}%>


<div class="content-center">
	<div class="user-info">
		<%= render :partial=>"users/user_info", :locals=>{:user=>@user} %>
	</div>

	<div class="user-title">
		<h4>Comments (<%=@comments.count %>)</h4>
	</div>

	<div class="user-content user-comments">
		<table class="table">
			<tr>
				<th class="user-show-comment-table-index"></th>
				<th class="user-show-comment-table-article">Article</th>
				<th class="user-show-comment-table-comment-content">Comment</th>
				<th class="user-show-comment-table-update">Date Time</th>
			</tr>
			<% @comments.each_with_index do |c,index| %>
				<% if c.article %>
			<tr>
				<td class="user-show-comment-table-index"><%= index+1 %></td>
				<td class="user-show-comment-table-article">
					<%= link_to c.article.title, article_path(c.article) %>
				</td>
				<td class="user-show-comment-table-comment-content">
					<%= link_to c.content, article_path(c.article)%>
				</td>
				<td class="user-show-comment-table-update">
					<%= time_ago_in_words(c.updated_at) %>
				</td>
			</tr>
				<% end %><!-- if c.article -->
			<% end %><!-- @user.comments .order -->
		</table>
	</div>
</div>

app/views/users/draft.html.erb
<%= render :partial => "side_bar/user", :locals =>{}%>


<div class="content-center">
	<div class="user-info">
		<%= render :partial=>"users/user_info", :locals=>{:user=>@user} %>
	</div>

	<div class="user-title">
		<h4>My draft articles (<%=@draft_articles.count%>)</h4>
	</div>

	<div class="user-content user-draft">
		<table class="table">
			<tr>
				<th class="index"></th>
				<th class="title">Title</th>
				<th class="category">Category</th>
				<th class="update">Update Date</th>
			</tr>

			<% @draft_articles.each_with_index do |da,index| %>
			<tr>
				<td class="index">
					<%= index +1 %>
				</td>
				<td class="title">
					<%= link_to da.title, edit_article_path(da) %>
				</td>
				<td class="category">
						<% category = '' %>
						<% da.categories.each do |c| %>
							<% category += c.name + ' ' %>
						<% end %>
						<%= category %>
				</td>
				<td class="update">
					<%= da.updated_at %>
				</td>
				<% end %><!-- @draft_articles.each_with_index -->
			</tr>
		</table>
	</div>
</div>

app/views/users/favorite.html.erb
<%= render :partial => "side_bar/user", :locals =>{}%>


<div class="content-center">
	<div class="user-info">
		<%= render :partial=>"users/user_info", :locals=>{:user=>@user} %>
	</div>

	<div class="user-title">
		<h4>My favorite articles (<%= @favorite_articles.count %>)</h4>
	</div>

	<div class="user-content user-favorite">
		<table class="table">
			<tr>
				<th class="index"></th>
				<th class="title">Title</th>
				<th class="poster">Poster</th>
				<th class="comment">Comment</th>
				<th class="update">Update Date</th>
				<th class="remove"></th>
			</tr>

			<% @favorite_articles.each_with_index do |fa,index|%>
			<tr>
				<td class="index"><%= index+1 %></td>
				<td class="title"><%= link_to fa.title, article_path(fa)%></td>
				<td class="poster"><%= link_to fa.user.username, user_path(fa.user)%></td>
				<td class="comment"><%= fa.comments.count %></td>
				<td class="update"><%=fa.updated_at%></td>
				<td class="remove"><%= button_to "Remove", remove_favorite_article_path(fa), :class=>"btn btn-warning",:data=>{:confirm=>"Are you sure?"} %>
				</td>
			</tr>
			<% end %><!-- @user.favorite_articles.each_with_index -->
		</table>
	</div>
</div>

app/views/users/friends.html.erb
<%= render :partial => "side_bar/user", :locals =>{}%>


<div class="content-center">
	<div class="user-info">
		<div><%= image_tag avatar_url(@user)%></div>
		<h3><%= @user.username %></h3>
	</div>


	<div class="user-content user-friends">


		<div class="my_invitations">
			<%= render :partial=>'friends_new.html',:locals=>{:invited_friendships=>@invited_friendships} %>
		</div><!-- invitation -->
		
		<div class="my_friends">
			<%= render :partial=>'friends_completed',:locals=>{:completed_friendships=>@completed_friendships} %>
		</div><!-- My_friends -->
		

		<div class="my_other_users">
			<%= render :partial=>'friends_other',:locals=>{:other_friendships=>@other_friendships} %>
		</div><!-- My_other_friends -->

	</div>	
</div><!-- content-center -->

<script>
	$('.my_friends').on('change','.relation_select',function(){
		 $.ajax({
	    type: "POST",
	    url: $(this).data('url') + "?friend_relation_tag_id="+$(this).val(),
	    dataType: "JSON",
	    success: function(data) {

		    }
		  });
	});

</script>

app/views/users/friends_update.js.erb
$('.user-friends .my_invitations').html("<%= j (render :partial=>'users/friends_new', :locals=>{:invited_friendships=>@invited_friendships})%>");
$('.user-friends .my_friends').html("<%= j (render :partial=>'users/friends_completed', :locals=>{:completed_friendships=>@completed_friendships})%>");
$('.user-friends .my_other_users').html("<%= j (render :partial=>'users/friends_other', :locals=>{:other_friendships=>@other_friendships})%>");

app/views/users/like_articles.html.erb
<%= render :partial => "side_bar/user", :locals =>{}%>


<div class="content-center">
	<div class="user-info">
		<%= render :partial=>"users/user_info", :locals=>{:user=>@user} %>
	</div>

	<div class="user-title">
		<h4>My like articles (<%= @like_articles.count %>)</h4>
	</div>

	<div class="user-content user-like">
		<table class="table">
			<tr>
				<th class="index"></th>
				<th class="title">Title</th>
				<th class="poster">Poster</th>
				<th class="likes">Likes</th>
				<th class="update">Update Date</th>
				<th class="remove"></th>
			</tr>

			<% @like_articles.each_with_index do |la,index|%>
				<% like = Like.find_by_user_article(@user,la) %>
			<tr>
				<td class="index"><%= index+1 %></td>
				<td class="title"><%= link_to la.title, article_path(la)%></td>
				<td class="poster"><%= link_to la.user.username, user_path(la.user)%></td>
				<td class="likes"><%= la.likes_count %></td>
				<td class="update"><%=la.updated_at%></td>
				<td class="remove"><%= render :partial=>"articles/like",:locals=>{:like=>like, :article=>la} %>
				</td>
			</tr>
			<% end %><!-- @user.favorite_articles.each_with_index -->
		</table>
	</div>
</div>

<script>

$('.user-like .btn-info').on('ajax:success', function(){

  $(this).closest("tr").remove();
  
});

</script>

app/views/users/profile_edit.html.erb
<%= render :partial => "side_bar/user", :locals =>{}%>

<div class="content-center">
	<div class="user-info">
		<div><%= image_tag avatar_url(@user)%></div>
		<h3><%= @user.username %></h3>
	</div>

	<div class="user-content user-profile">
		<h4><%= @user.username%> 's profile</h4>
		<% if @user == current_user  %>
		<%= link_to "Back to user",profile_user_path(@user)%>
		<% end %>

	<%= form_for @user, :url=>profile_user_path(@user), :method=>:patch do |f|%>
		<%= f.fields_for :user_profile, @user.user_profile do |u| %>
		<table class="table">
			<tr>
				<td><%= f.label :username, "username" %> </td>
				<td><%= f.text_field :username %> </td>
			</tr>
			<tr>
				<td><%= u.label :first_name, "First Name" %> </td>
				<td><%= u.text_field :first_name %> </td>
			</tr>
			<tr>
				<td><%= u.label :last_name, "Last Name" %> </td>
				<td><%= u.text_field :last_name %> </td>
			</tr>
			<tr>
				<td><%= u.label :english_name, "English Name" %> </td>
				<td><%= u.text_field :english_name %> </td>
			</tr>
			<tr>
				<td><%= u.label :birthdate, "Birth Date" %> </td>
				<td><%= u.text_field :birthdate %> </td>
			</tr>
			<tr>
				<td><%= u.label :intro, "Intro" %> </td>
				<td><%= u.text_area :intro %> </td>
			</tr>
			<tr><td>Total visit</td><td><%= @user.post_articles.count %></td></tr>
			<tr><td>Total posting articles</td><td><%= @user.post_articles.count	%></td></tr>
			<tr><td>Total replying articles</td><td><%= @user.reply_articles.count %></td></tr>
		</table>
		<%= f.submit "Update" %>
		<% end %><!-- fields_for -->
	<% end %><!-- form for -->
	</div>
</div>

app/views/users/profile_show.html.erb
<%= render :partial => "side_bar/user", :locals =>{}%>

<div class="content-center">
	<div class="user-info">
		<div><%= image_tag avatar_url(@user)%></div>
		<h3><%= @user.username %></h3>
	</div>

	<div class="user-content user-profile">
		<h4><%= @user.username%> 's profile</h4>
		<% if @user == current_user  %>
		<%= link_to "Edit",edit_profile_user_path(@user), :class=>"btn btn-info"%>
		<% end %>

		<table class="table">
			<tr>
				<td>First Name</td>
				<td><%= @user.user_profile.try(:first_name)  %></td>
			</tr>
			<tr><td>Username</td><td><%= @user.username %></td></tr>
			<tr><td>Last Name</td><td><%= @user.user_profile.try(:last_name)		%></td></tr>
			<tr><td>English Name</td><td><%= @user.user_profile.try(:english_name)%></td></tr>
			<tr><td>Birthdate</td><td><%= @user.user_profile.try(:birthdate)   %></td></tr>
			<tr><td>Intro</td><td><%= @user.user_profile.try(:intro)   %></td></tr>
			<tr><td>Total visit</td><td><%= @user.post_articles.count %></td></tr>
			<tr><td>Total posting articles</td><td><%= @user.post_articles.count	%></td></tr>
			<tr><td>Total replying articles</td><td><%= @user.reply_articles.count %></td></tr>
		</table>
	</div>
</div>