config/routes.rb
Rails.application.routes.draw do

  get 'about' => "abouts#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: :show do
    
    resource :profile
    member do
      get :articles
      get :comments
      get :like_articles

      get :draft
      get :favorite

      get :friends
    end
  end

  resources :friends do 
    member do
      get :send_invitation
      get :cancel_invitation
      get :accept_invitation
      get :ignore_invitation
      get :reject_invitation
      get :block_my_friend
      get :unblock_my_friend
      post :select_relation_tag
    end
  end

  resources :articles do
    resources :comments
    member do
      post :add_favorite
      post :remove_favorite
      post :like
      get :like_users
      post :move
    end
  end

  namespace :admin do
    resources :articles
    resources :categories
    resources :users
  end

  root :to => 'articles#index'

end

app/views/side_bar/_admin.html.erb
<div class="content-left admin-content-left">
	<div class="do-it user-back">
		<%= link_to "Back to Forum",articles_path, :class=>"btn btn-primary" %>

	</div>
	<ul class="list">
		<li><%= link_to "articles", admin_articles_path %></li>
		<li><%= link_to "categories", admin_categories_path %></li>
		<li><%= link_to "users", admin_users_path %></li>
		<!-- <li class='content-left-hightlighted'>".html_safe : "<li>".html_safe%>  -->
	</ul>
</div><!-- content-left -->

app/views/side_bar/_category.html.erb
<div class="content-left">
	<div class="do-it">
		<% if path == "post" %>
			<% if current_user %>
				<%= link_to "Post Article", new_article_path, :class=>"btn btn-primary" %>
			<% else %>
				<%= link_to "Login to Post", new_session_path(:user), :class=>"btn btn-primary" %>
			<% end %>
		<% elsif path == "back" %>
			<%= link_to "Back to Forum",articles_path, :class=>"btn btn-primary" %>
		<% end %>
	</div>

	<ul class="list">
		<li>
			<%= link_to "All", articles_path, :id=> @category == nil ? "highlighted" : "" %>
		</li>
		<%  @categories.each_with_index do |c,index| %>
			<li>
			<%= link_to c.name, articles_path(:category_id=>c.id), :id=> @category == c ? "highlighted" : "" %>
		</li>
		<% end %>
	</ul>
</div><!-- content-left -->

app/views/side_bar/_user.html.erb
<div class="content-left">
	<div class="do-it user-back">
		<%= link_to "Back to forum", articles_path, :class=>"btn btn-info"%>
	</div>
	<ul class="list">
		<li><%= link_to "Profile", user_profile_path(@user), :id=>@user_profile ? "highlighted" : "" %></li>
		<li><%= link_to "Article", articles_user_path(@user), :id=>@post_articles ? "highlighted" : ""  %></li>
		<li><%= link_to "Comments", comments_user_path(@user), :id=>@comments ? "highlighted" : ""  %></li>

		<% if @user == current_user %>
			<li><%= link_to "Favorites", favorite_user_path(@user), :id=>@favorite_articles ? "highlighted" : ""  %></li>
			<li><%= link_to "Draft", draft_user_path(@user), :id=>@draft_articles ? "highlighted" : ""  %></li>
			<li><%= link_to "Likes", like_articles_user_path(@user), :id=>@like_articles ? "highlighted" : "" %></li>
			<li><%= link_to "Friends", friends_user_path(@user), :id=>@friendships ? "highlighted" : ""  %></li>

		<% end %>

	</ul>
</div><!-- content-left -->